# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Render the checkpoint **alias** recipes under ``modelopt_recipes/models/``.

Most released checkpoints are reproduced by a recipe that is not checkpoint-specific --
a ``general/`` scheme, or a ``huggingface/<model_type>/`` one. Those releases still get
an entry in the ``models/`` tier so that every published checkpoint is findable at its
own hub path, but the entry is a thin **alias**: it delegates its whole body to the
recipe that reproduces it with a top-level ``$import`` and supplies only its own
``metadata``. Nothing is duplicated, and editing the base recipe changes every alias.

Aliases are generated rather than hand-written so their headers cannot drift from
``recipe_map.json``; ``tests/unit/recipe/test_published_checkpoint_recipes.py``
re-renders them and fails if a checked-in file differs.

Usage::

    python tools/recipe_backfill/render_aliases.py --check   # verify they are up to date
    python tools/recipe_backfill/render_aliases.py           # rewrite them
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
REPO_ROOT = HERE.parents[1]
RECIPES_ROOT = REPO_ROOT / "modelopt_recipes"
MODELS_ROOT = RECIPES_ROOT / "models"

#: Marker naming this file as the generator, used to find previously generated aliases.
GENERATED_MARKER = "# Generated by tools/recipe_backfill/render_aliases.py"

LICENSE_HEADER = (REPO_ROOT / "LICENSE_HEADER").read_text(encoding="utf-8")

_TEMPLATE = """{license}

{marker} -- do not edit by hand.
#
# Alias recipe for {source}.
#
# It records that {checkpoint} is reproduced by
# `{base}`
# with no checkpoint-specific changes, and it is how that release is found at its own
# hub path rather than only under the recipe's own tier.
#
# The whole body -- `quantize`, its algorithm and every `quant_cfg` entry -- is imported
# from that recipe; only `metadata` is local. Edit the base recipe to change what this
# produces.
#
# See `modelopt_recipes/published_checkpoints.md` for the full checkpoint-to-recipe
# index, and `modelopt_recipes/models/README.md` for when a checkpoint warrants a recipe
# of its own instead of an alias.

imports:
  base: {base}

$import: base
metadata:
  recipe_type: ptq
  description: >-
    {source} as published in {checkpoint}.
    Alias for `{base}`,
    which reproduces this checkpoint unchanged.
"""


def _license_comment() -> str:
    return "\n".join(f"# {line}".rstrip() for line in LICENSE_HEADER.splitlines())


def _spec(value) -> dict:
    return {"recipe": value} if isinstance(value, str) else dict(value)


def source_model(checkpoint_id: str, spec: dict, entries: dict) -> str | None:
    """The checkpoint's source weights: an explicit ``source_model``, else ``base_model``."""
    return spec.get("source_model") or (entries.get(checkpoint_id) or {}).get("base_model")


def alias_path(source: str, base_recipe: str) -> Path:
    """Where the alias for *base_recipe* on *source* lives."""
    return MODELS_ROOT / source / "ptq" / f"{base_recipe.rsplit('/', 1)[1]}.yaml"


def alias_recipe(source: str, base_recipe: str) -> str:
    """The alias's ``modelopt_recipes``-relative recipe path (no suffix)."""
    return str(alias_path(source, base_recipe).relative_to(RECIPES_ROOT).with_suffix(""))


def planned_aliases() -> dict[Path, str]:
    """Map every alias file path to its rendered content."""
    snapshot = json.loads((HERE / "published_checkpoints.json").read_text(encoding="utf-8"))
    mapping = json.loads((HERE / "recipe_map.json").read_text(encoding="utf-8"))
    entries = {e["id"]: e for e in snapshot["checkpoints"]}

    out: dict[Path, str] = {}
    for checkpoint_id, raw in sorted(mapping["recipes"].items()):
        spec = _spec(raw)
        base = spec["recipe"]
        if base.startswith("models/"):
            continue  # already has a checkpoint-specific recipe
        source = source_model(checkpoint_id, spec, entries)
        if not source:
            raise ValueError(
                f"{checkpoint_id} has no base_model in published_checkpoints.json; add a "
                "'source_model' to its recipe_map.json entry so its alias folder can be keyed."
            )
        path = alias_path(source, base)
        if path in out:
            raise ValueError(f"two checkpoints would render the same alias file: {path}")
        out[path] = _TEMPLATE.format(
            license=_license_comment(),
            marker=GENERATED_MARKER,
            source=source,
            checkpoint=checkpoint_id,
            base=base,
        )
    return out


def existing_aliases() -> set[Path]:
    """Every alias file previously written by this script."""
    return {
        p for p in MODELS_ROOT.rglob("*.yaml") if GENERATED_MARKER in p.read_text(encoding="utf-8")
    }


def main() -> int:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if any alias is out of date")
    args = ap.parse_args()

    planned = planned_aliases()
    stale = existing_aliases() - set(planned)
    outdated = [
        path
        for path, content in planned.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]

    if args.check:
        if outdated or stale:
            for path in sorted(outdated):
                print(f"out of date: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            for path in sorted(stale):
                print(f"no longer mapped: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            print(f"re-run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{len(planned)} alias recipes are up to date")
        return 0

    for path in sorted(stale):
        path.unlink()
        print(f"removed {path.relative_to(REPO_ROOT)}")
    for path, content in sorted(planned.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(planned)} alias recipes under {MODELS_ROOT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
