# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Render ``modelopt_recipes/published_checkpoints.md`` from the backfill data.

The table is generated so it cannot drift from ``recipe_map.json``;
``tests/unit/recipe/test_published_checkpoint_recipes.py`` re-renders it and fails if
the checked-in file differs.

Usage::

    python tools/recipe_backfill/render_index.py --check   # verify it is up to date
    python tools/recipe_backfill/render_index.py           # rewrite it
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from render_aliases import alias_recipe, source_model

HERE = Path(__file__).parent
REPO_ROOT = HERE.parents[1]
OUTPUT = REPO_ROOT / "modelopt_recipes" / "published_checkpoints.md"

_HEADER = """<!-- Generated by tools/recipe_backfill/render_index.py -- do not edit by hand. -->

# Published checkpoints and the recipes that reproduce them

Every checkpoint **NVIDIA publishes** in the [Inference Optimized Checkpoints][collection]
collection, paired with the recipe in this package that reproduces its quantization
layout. The collection also carries partner-published checkpoints; those are listed under
[Not covered](#not-covered) rather than given recipes.

**Coverage is partial.** The backfill lands one source-model org per branch, so a
released checkpoint may not be listed here yet; run
`python tools/recipe_backfill/verify_recipes.py` to see which are still uncovered.

Use it in both directions: to re-create a released checkpoint from its source weights, or
to find a validated starting recipe for a model whose architecture resembles one of these.

Each pairing is checked automatically. `tools/recipe_backfill/published_checkpoints.json`
records the format of every module in every released checkpoint (read from its
`hf_quant_config.json`, the exported scale tensors and the safetensors headers), and
`tests/unit/recipe/test_published_checkpoint_recipes.py` replays each recipe's
`quant_cfg` over those module names and asserts the result matches. Regenerate both with
`tools/recipe_backfill/scan_collection.py`.

Run a recipe with:

```bash
python examples/hf_ptq/hf_ptq.py \\
    --pyt_ckpt_path <source checkpoint> \\
    --recipe <recipe path from the table> \\
    --export_path <output>
```

[collection]: https://huggingface.co/collections/nvidia/inference-optimized-checkpoints-with-model-optimizer

## Checkpoints

| Published checkpoint | Source model | Recipe |
|---|---|---|
"""

_UNMAPPED_HEADER = """
### Not covered

| Published checkpoint | Why there is no recipe |
|---|---|
"""


def _hub_link(model_id: str) -> str:
    return f"[`{model_id}`](https://huggingface.co/{model_id})"


def render() -> str:
    """Return the full Markdown body of the published-checkpoint index."""
    snapshot = json.loads((HERE / "published_checkpoints.json").read_text(encoding="utf-8"))
    mapping = json.loads((HERE / "recipe_map.json").read_text(encoding="utf-8"))
    entries = {e["id"]: e for e in snapshot["checkpoints"]}

    lines = [_HEADER]
    for checkpoint_id, raw in sorted(mapping["recipes"].items(), key=lambda kv: kv[0].lower()):
        spec = {"recipe": raw} if isinstance(raw, str) else raw
        base = spec["recipe"]
        source = source_model(checkpoint_id, spec, entries)

        if base.startswith("models/"):
            recipe_cell = f"`{base}`"
        else:
            # Aliased: the checkpoint's own path is what a user should pass.
            recipe_cell = f"`{alias_recipe(source, base)}`<br>alias for `{base}`"
        if spec.get("approximate"):
            recipe_cell += " *(approximate)*"
        notes = [spec[key] for key in ("approximate", "note") if spec.get(key)]
        if notes:
            recipe_cell += "<br>" + "<br>".join(notes)

        lines.append(
            f"| {_hub_link(checkpoint_id)} | {_hub_link(source) if source else '—'} "
            f"| {recipe_cell} |\n"
        )

    lines.append(_UNMAPPED_HEADER)
    for checkpoint_id, reason in sorted(mapping["unmapped"].items(), key=lambda kv: kv[0].lower()):
        lines.append(f"| {_hub_link(checkpoint_id)} | {reason} |\n")
    return "".join(lines)


def main() -> int:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args()

    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != rendered:
            print(f"{OUTPUT} is out of date; re-run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
