job_name: MiniMax-M2.7-DFlash_thru32k_test_yarn
pipeline:
  global_vars:
    hf_model: /hf-local/MiniMaxAI/MiniMax-M2.7
  task_1:
    script: common/specdec_bench/run.sh
    args:
    - --dataset speed
    - --dataset_path /hf-local/nvidia/SPEED-Bench-Internal/throughput_32k
    - --engine VLLM
    - --speculative_algorithm DFLASH
    - --draft_model_dir /lustre/fsw/portfolios/coreai/users/yeyu/experiments/dflash_minimax_m2.7_training_lr1.2e-3/exported-checkpoint-20400-yarn
    - --block_size 8
    - --tp_size 4
    - --ep_size 4
    - --concurrency 8
    - --num_requests 80
    - --output_length 4096
    - --max_seq_len 40960
    - --trust_remote_code
    - --aa_timing
    - --show_progress
    - --save_dir /lustre/fsw/portfolios/coreai/users/yeyu/experiments/dflash_minimax_m2.7_training_lr1.2e-3/thru32k_results_yarn
    environment:
    - HF_MODEL_CKPT: <<global_vars.hf_model>>
    - HF_LOCAL: /hf-local
    slurm_config:
      _factory_: slurm_factory
      nodes: 1
      ntasks_per_node: 1
      gpus_per_node: 8
      container: vllm/vllm-openai:nightly
