# SPDX-FileCopyrightText: Copyright (c) 2024 AMD, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""AMD Model Card generator for quantized models.

Generates a structured summary of an AMD FP8/INT8 quantized model
for documentation and deployment tracking.
"""
from __future__ import annotations
import json
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import torch


def generate_amd_model_card(
    model: "torch.nn.Module",
    model_name: str,
    benchmark_results: "dict | None" = None,
    scales_path: "str | None" = None,
    output_path: "str | None" = None,
) -> str:
    """Generate an AMD FP8 model card documenting quantization details.
    
    Args:
        model: Quantized model
        model_name: Human-readable model name (e.g. "LLaMA-70B")
        benchmark_results: Dict of {batch_size: speedup} from benchmarking
        scales_path: Path to saved FP8 scales JSON
        output_path: If set, saves card to this file
    
    Returns:
        Model card as markdown string
    
    Example:
        card = generate_amd_model_card(
            model_fp8, "LLaMA-70B",
            benchmark_results={1: 1.81, 4: 1.83, 256: 1.64},
            scales_path="llama70b_scales.json"
        )
        print(card)
    """
    import torch
    from modelopt._rocm_compat import count_fp8_layers, get_gpu_arch, is_fp8_supported
    
    layer_counts = count_fp8_layers(model)
    param_count = sum(p.numel() for p in model.parameters())
    arch = get_gpu_arch() if is_fp8_supported() else "N/A"
    
    # Model size in memory
    fp8_params = sum(
        p.numel() for name, p in model.named_parameters()
        if p.dtype == torch.float8_e4m3fnuz
    )
    int8_params = sum(
        p.numel() for name, p in model.named_parameters()
        if p.dtype == torch.int8
    )
    fp16_params = param_count - fp8_params - int8_params
    
    size_fp8_gb = fp8_params / 1e9  # 1 byte each
    size_int8_gb = int8_params / 1e9
    size_fp16_gb = fp16_params * 2 / 1e9
    total_size_gb = size_fp8_gb + size_int8_gb + size_fp16_gb
    fp16_baseline_gb = param_count * 2 / 1e9
    
    now = datetime.now().strftime("%Y-%m-%d")
    
    card = f"""# AMD FP8 Model Card: {model_name}

**Generated:** {now}  
**Hardware:** AMD MI300X (gfx942/CDNA3) | ROCm 7.0+  
**Quantization:** FP8 E4M3FNUZ (float8_e4m3fnuz) via hipBLASLt  

## Model Summary

| Property | Value |
|----------|-------|
| Total parameters | {param_count:,} ({param_count/1e9:.1f}B) |
| FP8 Linear layers | {layer_counts['fp8_linear']} |
| Remaining FP16 layers | {layer_counts['fp16_linear']} |
| Quantization coverage | {layer_counts['quantized_fraction']*100:.0f}% |
| Model size (quantized) | {total_size_gb:.2f} GB |
| Model size (FP16 baseline) | {fp16_baseline_gb:.2f} GB |
| Memory reduction | {(1 - total_size_gb/fp16_baseline_gb)*100:.0f}% |

## Quantization Details

- **Format:** `torch.float8_e4m3fnuz` (AMD CDNA exponent bias, NOT NVIDIA E4M3)
- **Weight quantization:** Per-tensor, static (pre-cast at deployment load time)
- **Input quantization:** Per-tensor, static (scale from AMD_FP8_DEFAULT_CFG calibration)
- **Dispatch:** `torch._scaled_mm` → hipBLASLt FP8 kernel
- **Calibration config:** `mtq.AMD_FP8_DEFAULT_CFG` (modelopt QuantizerCfgEntry schema)
"""
    
    if scales_path:
        card += f"- **Saved scales:** `{scales_path}`\n"
    
    if benchmark_results:
        card += f"""
## Benchmark Results (AMD MI300X, gfx942)

| Batch Size | Speedup vs FP16 |
|-----------|----------------|
"""
        for bs, spd in sorted(benchmark_results.items()):
            bar = "▓" * int(spd * 5)
            card += f"| {bs} | {spd:.2f}× {bar} |\n"
    
    card += f"""
## Usage

```python
import modelopt.torch.quantization as mtq
from modelopt._rocm_compat import amd_deploy_model

# Fast startup (with pre-computed scales)
model = amd_deploy_model(model, scales_path="{scales_path or 'fp8_scales.json'}")

# Or calibrate from scratch
model = amd_deploy_model(model, calibration_data=x_cal,
                          save_scales_to="fp8_scales.json")
```

## Notes

- FP8 speedup requires BS≥64 for H=4096 models; BS≥1 for H≥8192 (LLaMA-70B)
- `float8_e4m3fnuz` ≠ `float8_e4m3fn` — AMD CDNA has different exponent bias
- `torch._int_mm` does NOT dispatch to hipBLASLt; use FP8 for deployment latency
- For INT8 throughput, export to ONNX and use `mgx.quantize_int8()` via MIGraphX

---
*Generated by ROCm-Model-Optimizer AMD FP8 pipeline*
"""
    
    if output_path:
        with open(output_path, "w") as f:
            f.write(card)
        print(f"Model card saved: {output_path}")
    
    return card
