name: PR Gate

on:
  workflow_call:
    inputs:
      files:
        description: "Newline-separated list of file patterns to watch for changes"
        required: true
        type: string
    outputs:
      any_changed:
        description: "Whether any relevant files changed"
        value: ${{ jobs.check-file-changes.outputs.any_changed }}

jobs:
  check-file-changes:
    if: startsWith(github.ref, 'refs/heads/pull-request/')
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-tests.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: get-pr-info
        uses: nv-gha-runners/get-pr-info@main
      # Get commit from main branch that is present in the PR to use as base for changed files
      - id: calculate-merge-base
        env:
          PR_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
          BASE_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
        run: |
          (echo -n "merge-base="; git merge-base "$BASE_SHA" "$PR_SHA") | tee --append "${GITHUB_OUTPUT}"
      - name: Check for changes in test-relevant directories
        id: changed-tests
        uses: step-security/changed-files@v46.0.5
        with:
          base_sha: ${{ steps.calculate-merge-base.outputs.merge-base }}
          sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
          files: ${{ inputs.files }}
          fail_on_initial_diff_error: true
  wait-checks:
    needs: [check-file-changes]
    if: needs.check-file-changes.outputs.any_changed == 'true'
    uses: ./.github/workflows/_wait_for_checks.yml
    permissions:
      checks: read
    secrets: inherit
    with:
      match_pattern: "^linux$" # Wait for Unit tests / linux (DCO is a prerequisite of linux)
      delay: 300s
